# Importar librerias

In [ ]:
import numpy as np

# Crear Array

In [ ]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.array(lista)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.array(lista)

In [ ]:
type(arr)

numpy.ndarray

# Crear Matriz

In [ ]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Indexing

## Indexing Array

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1]

2

In [ ]:
arr[0] + arr[5]

7

## Indexing Matriz

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[0]

array([1, 2, 3])

In [ ]:
matriz[1]

array([4, 5, 6])

In [ ]:
matriz[2]

array([7, 8, 9])

In [ ]:
matriz[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[0,2]

3

## Indexing amplios

### Para mostrar los datos DESDE una posición inicial hasta ANTES de una posición final:

In [ ]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Para mostrar los datos dando saltos de 3 en 3:

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[::3]

array([1, 4, 7])

### Para mostrar posiciones finales

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[-1]

9

In [ ]:
arr[-3:]

array([7, 8, 9])

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

### Accede primero a los arrays desde la posición 1 hasta el final. Luego se acceden desde la posición 0 hasta antes de la posición 2.

In [ ]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])